spring:

  application:
    name: spring-begin
  datasource:
    url: jdbc:mysql://localhost:3306/news_db
    username: root
    password: make5211314
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      host: localhost
      password: 123456
      port: 6379
      database: 1
  cache:
    type: redis
  jpa:
    open-in-view: false


mybatis-plus:

  global-config:
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:

  servlet:
    context-path: /api/v0
  port: 7230



jwt:
  expire-time: 120
  sign: make-forwardforever-top



