host:
  domain-name: www.forwardforever.top
spring:
  datasource:
    url: jdbc:mysql://${host.domain-name}:3306/news_db
    username: make
    password: make5211314
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${host.domain-name}
      password: make5211314
      port: 6379
      database: 1


